# 由前端 src/config/models.ts 转换而来，seed 时导入 models 表
from dataclasses import dataclass

@dataclass
class ModelSeed:
    id: str
    name: str
    free: bool = False
    vision: bool = False

MODEL_SEEDS: list[ModelSeed] = [
    ModelSeed(id="THUDM/GLM-4-9B-0414", name="GLM-4-9B", free=True, vision=False),
    ModelSeed(id="Qwen/Qwen2.5-7B-Instruct", name="Qwen2.5-7B-Instruct", free=True, vision=False),
    ModelSeed(id="ByteDance-Seed/Seed-OSS-36B-Instruct", name="Seed-OSS-36B-Instruct", free=False, vision=False),
    ModelSeed(id="LoRA/Qwen/Qwen2.5-14B-Instruct", name="Qwen2.5-14B-Instruct (LoRA)", free=False, vision=False),
    ModelSeed(id="LoRA/Qwen/Qwen2.5-32B-Instruct", name="Qwen2.5-32B-Instruct (LoRA)", free=False, vision=False),
    ModelSeed(id="LoRA/Qwen/Qwen2.5-72B-Instruct", name="Qwen2.5-72B-Instruct (LoRA)", free=False, vision=False),
    ModelSeed(id="MiniMaxAI/MiniMax-M2.5", name="MiniMax-M2.5", free=False, vision=False),
    ModelSeed(id="Pro/MiniMaxAI/MiniMax-M2.5", name="MiniMax-M2.5 (Pro)", free=False, vision=False),
    ModelSeed(id="Pro/Qwen/Qwen2.5-7B-Instruct", name="Qwen2.5-7B-Instruct (Pro)", free=False, vision=False),
    ModelSeed(id="Pro/deepseek-ai/DeepSeek-R1", name="DeepSeek-R1 (Pro)", free=False, vision=False),
    ModelSeed(id="Pro/deepseek-ai/DeepSeek-V3", name="DeepSeek-V3 (Pro)", free=False, vision=False),
    ModelSeed(id="Pro/deepseek-ai/DeepSeek-V3.1-Terminus", name="DeepSeek-V3.1-Terminus (Pro)", free=False, vision=False),
    ModelSeed(id="Pro/deepseek-ai/DeepSeek-V3.2", name="DeepSeek-V3.2 (Pro)", free=False, vision=False),
    ModelSeed(id="Pro/moonshotai/Kimi-K2.6", name="Kimi-K2.6 (Pro)", free=False, vision=False),
    ModelSeed(id="THUDM/GLM-Z1-9B-0414", name="GLM-Z1-9B", free=True, vision=False),
    ModelSeed(id="Pro/zai-org/GLM-5.1", name="GLM-5.1 (Pro)", free=False, vision=False),
    ModelSeed(id="PaddlePaddle/PaddleOCR-VL-1.5", name="PaddleOCR-VL-1.5", free=True, vision=True),
    ModelSeed(id="Qwen/Qwen2.5-14B-Instruct", name="Qwen2.5-14B-Instruct", free=False, vision=False),
    ModelSeed(id="Qwen/Qwen2.5-32B-Instruct", name="Qwen2.5-32B-Instruct", free=False, vision=False),
    ModelSeed(id="Qwen/Qwen2.5-72B-Instruct", name="Qwen2.5-72B-Instruct", free=False, vision=False),
    ModelSeed(id="Qwen/Qwen2.5-72B-Instruct-128K", name="Qwen2.5-72B-Instruct-128K", free=False, vision=False),
    ModelSeed(id="Qwen/Qwen3-14B", name="Qwen3-14B", free=False, vision=False),
    ModelSeed(id="Qwen/Qwen3-30B-A3B-Instruct-2507", name="Qwen3-30B-A3B-Instruct", free=False, vision=False),
    ModelSeed(id="Qwen/Qwen3-32B", name="Qwen3-32B", free=False, vision=False),
    ModelSeed(id="Qwen/Qwen3-8B", name="Qwen3-8B", free=True, vision=False),
    ModelSeed(id="Qwen/Qwen3-Coder-30B-A3B-Instruct", name="Qwen3-Coder-30B-A3B-Instruct", free=False, vision=False),
    ModelSeed(id="Qwen/Qwen3-Omni-30B-A3B-Captioner", name="Qwen3-Omni-30B-A3B-Captioner", free=False, vision=True),
    ModelSeed(id="Qwen/Qwen3-Omni-30B-A3B-Instruct", name="Qwen3-Omni-30B-A3B-Instruct", free=False, vision=True),
    ModelSeed(id="Qwen/Qwen3-Omni-30B-A3B-Thinking", name="Qwen3-Omni-30B-A3B-Thinking", free=False, vision=True),
    ModelSeed(id="Qwen/Qwen3-VL-30B-A3B-Instruct", name="Qwen3-VL-30B-A3B-Instruct", free=False, vision=True),
    ModelSeed(id="Qwen/Qwen3-VL-30B-A3B-Thinking", name="Qwen3-VL-30B-A3B-Thinking", free=False, vision=True),
    ModelSeed(id="Qwen/Qwen3-VL-32B-Instruct", name="Qwen3-VL-32B-Instruct", free=False, vision=True),
    ModelSeed(id="Qwen/Qwen3-VL-32B-Thinking", name="Qwen3-VL-32B-Thinking", free=False, vision=True),
    ModelSeed(id="Qwen/Qwen3-VL-8B-Instruct", name="Qwen3-VL-8B-Instruct", free=False, vision=True),
    ModelSeed(id="Qwen/Qwen3-VL-8B-Thinking", name="Qwen3-VL-8B-Thinking", free=False, vision=True),
    ModelSeed(id="Qwen/Qwen3.5-122B-A10B", name="Qwen3.5-122B-A10B", free=False, vision=False),
    ModelSeed(id="Qwen/Qwen3.5-27B", name="Qwen3.5-27B", free=False, vision=False),
    ModelSeed(id="Qwen/Qwen3.5-35B-A3B", name="Qwen3.5-35B-A3B", free=False, vision=False),
    ModelSeed(id="Qwen/Qwen3.5-397B-A17B", name="Qwen3.5-397B-A17B", free=False, vision=False),
    ModelSeed(id="Qwen/Qwen3.5-4B", name="Qwen3.5-4B", free=True, vision=False),
    ModelSeed(id="Qwen/Qwen3.5-9B", name="Qwen3.5-9B", free=False, vision=False),
    ModelSeed(id="Qwen/Qwen3.6-27B", name="Qwen3.6-27B", free=False, vision=False),
    ModelSeed(id="Qwen/Qwen3.6-35B-A3B", name="Qwen3.6-35B-A3B", free=False, vision=False),
    ModelSeed(id="THUDM/GLM-4-32B-0414", name="GLM-4-32B", free=False, vision=False),
    ModelSeed(id="tencent/Hunyuan-MT-7B", name="Hunyuan-MT-7B", free=True, vision=False),
    ModelSeed(id="deepseek-ai/DeepSeek-OCR", name="DeepSeek-OCR", free=False, vision=True),
    ModelSeed(id="deepseek-ai/DeepSeek-R1", name="DeepSeek-R1", free=False, vision=False),
    ModelSeed(id="deepseek-ai/DeepSeek-R1-0528-Qwen3-8B", name="DeepSeek-R1-0528-Qwen3-8B", free=True, vision=False),
    ModelSeed(id="deepseek-ai/DeepSeek-V3", name="DeepSeek-V3", free=False, vision=False),
    ModelSeed(id="deepseek-ai/DeepSeek-V3.1-Terminus", name="DeepSeek-V3.1-Terminus", free=False, vision=False),
    ModelSeed(id="deepseek-ai/DeepSeek-V3.2", name="DeepSeek-V3.2", free=False, vision=False),
    ModelSeed(id="deepseek-ai/DeepSeek-V4-Flash", name="DeepSeek-V4-Flash", free=False, vision=False),
    ModelSeed(id="deepseek-ai/DeepSeek-V4-Pro", name="DeepSeek-V4-Pro", free=False, vision=False),
    ModelSeed(id="inclusionAI/Ling-flash-2.0", name="Ling-flash-2.0", free=False, vision=False),
    ModelSeed(id="inclusionAI/Ling-mini-2.0", name="Ling-mini-2.0", free=False, vision=False),
    ModelSeed(id="meituan-longcat/LongCat-2.0", name="LongCat-2.0", free=False, vision=False),
    ModelSeed(id="moonshotai/Kimi-K2.7-Code", name="Kimi-K2.7-Code", free=False, vision=False),
    ModelSeed(id="nex-agi/Nex-N2-Pro", name="Nex-N2-Pro", free=False, vision=False),
    ModelSeed(id="stepfun-ai/Step-3.5-Flash", name="Step-3.5-Flash", free=False, vision=False),
    ModelSeed(id="tencent/Hunyuan-A13B-Instruct", name="Hunyuan-A13B-Instruct", free=False, vision=False),
    ModelSeed(id="zai-org/GLM-4.5-Air", name="GLM-4.5-Air", free=False, vision=False),
    ModelSeed(id="zai-org/GLM-4.5V", name="GLM-4.5V", free=False, vision=True),
    ModelSeed(id="zai-org/GLM-5.2", name="GLM-5.2", free=False, vision=False),
]
